table 'Order reviews'
	lineageTag: b3b9d543-5331-4489-a02a-3df8f57af3e7

	column review_id
		dataType: string
		isHidden
		lineageTag: 24b5a282-9bcf-4acc-8af8-e9f81a37cfe2
		summarizeBy: none
		sourceColumn: review_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		isHidden
		lineageTag: f8f054cb-b2d7-46ae-ad9a-f7b6d70bb994
		summarizeBy: none
		sourceColumn: order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: fd78e00e-caf6-48c9-a5cc-97a0e5051eb1
		summarizeBy: none
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_comment_title
		dataType: string
		lineageTag: 7caaf1ea-ed2d-4634-9b10-2344d053bb8f
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: 9f4881de-00ed-4c95-947e-b03ead01c789
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	partition 'Order reviews' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\barvi\Documents\Proyectos\Proyecto_2-Olist\Data\olist_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"review_creation_date", "review_answer_timestamp"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"review_id"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates", {"order_id"})
				in
				    #"Removed Duplicates1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

